name: obers_ui_example
description: Example app showcasing obers_ui components.
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  obers_ui:
    path: ../
  obers_ui_autoforms:
    path: ../packages/obers_ui_autoforms
  obers_ui_charts:
    path: ../packages/obers_ui_charts

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
