name: obers_ui
description: A comprehensive Flutter UI kit with design tokens, responsive utilities, and accessible components.
version: 0.1.1
publish_to: 'none'
topics:
  - ui
  - widgets
  - design-system
  - theme

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  file_picker: ^8.1.0
  flutter:
    sdk: flutter
  intl: ^0.20.0
  shared_preferences: ^2.3.0
  web: ^1.1.1

flutter:
  fonts:
    - family: lucide
      fonts:
        - asset: lib/src/foundation/icons/lucide.ttf

dev_dependencies:
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  marqably_dart_qa_rules:
    git: git@git.duko.at:flutter/dart-flutter-qa-rules.git
  mocktail: ^1.0.4
  obers_ui_charts:
    path: packages/obers_ui_charts
  very_good_analysis: ^10.0.0
