name: obers_ui_widgetbook
description: Widgetbook showcase for the obers_ui design system.
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  obers_ui:
    path: ../
  widgetbook: ^3.10.0

dev_dependencies:
  very_good_analysis: ^7.0.0
