import 'dart:math' as math;

import 'package:flutter/foundation.dart';

/// The type of a chart scale, used for auto-inference and explicit override.
///
/// {@category Foundation}
enum OiScaleType {
  /// Maps a continuous numeric domain linearly to a pixel range.
  linear,

  /// Maps a continuous numeric domain logarithmically to a pixel range.
  logarithmic,

  /// Maps [DateTime] values linearly to a pixel range.
  time,

  /// Maps discrete string categories to pixel positions (no width).
  category,

  /// Maps discrete string categories to pixel bands with width.
  band,

  /// Maps discrete string categories to evenly-spaced point positions.
  point,

  /// Maps continuous numeric input to discrete output based on quantiles.
  quantile,

  /// Maps continuous numeric input to discrete output based on thresholds.
  threshold,
}

/// A tick mark generated by a scale.
///
/// {@category Foundation}
@immutable
class OiTick<T> {
  /// Creates an [OiTick].
  const OiTick({required this.value, required this.position});

  /// The domain value this tick represents.
  final T value;

  /// The pixel position of this tick within the output range.
  final double position;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OiTick<T> && other.value == value && other.position == position;

  @override
  int get hashCode => Object.hash(value, position);

  @override
  String toString() => 'OiTick($value @ $position)';
}

/// Abstract base for all chart scales.
///
/// A scale maps values from a domain (data space) to a range (pixel space).
/// Concrete implementations handle different data types and mapping
/// strategies.
///
/// Use `OiChartScale.inferType` to auto-detect the appropriate scale type
/// from sample data, or construct a specific scale directly.
///
/// {@category Foundation}
@immutable
abstract class OiChartScale<T> {
  /// Creates an [OiChartScale].
  const OiChartScale({
    required this.rangeMin,
    required this.rangeMax,
    this.clamp = false,
  });

  /// The minimum pixel value in the output range.
  final double rangeMin;

  /// The maximum pixel value in the output range.
  final double rangeMax;

  /// Whether to clamp output values to [rangeMin]–[rangeMax].
  final bool clamp;

  /// The type of this scale.
  OiScaleType get type;

  /// The extent of the output range in pixels.
  double get rangeExtent => rangeMax - rangeMin;

  /// The pixel distance for one minimal logical step of this scale.
  ///
  /// For continuous scales this is the number of pixels per one domain unit
  /// (linear), per one log-base unit (logarithmic), or per one millisecond
  /// (time). For discrete scales this is the spacing between adjacent items.
  ///
  /// Returns `0` when the scale has a degenerate (zero-width) domain or range.
  double get atom;

  /// Converts a domain [value] to a pixel position within the range.
  double toPixel(T value);

  /// Converts a pixel [position] back to the nearest domain value.
  T fromPixel(double position);

  /// Generates tick marks for this scale.
  ///
  /// For continuous scales, [count] suggests the desired number of ticks.
  /// For discrete scales, [count] is ignored and all values are returned.
  List<OiTick<T>> buildTicks({int count = 5});

  /// Generates tick marks constrained by [maxCount] and [axisLength].
  ///
  /// When [minSpacingPx] is provided, ticks are thinned so adjacent
  /// ticks are at least that many pixels apart.
  ///
  /// Delegates to [buildTicks] by default; concrete scales can override
  /// for smarter tick generation (e.g. nice values, endpoint inclusion).
  List<OiTick<T>> buildTicksConstrained({
    int? maxCount,
    double? minSpacingPx,
    double? axisLength,
  }) {
    var ticks = buildTicks(count: maxCount ?? 5);
    if (minSpacingPx != null && minSpacingPx > 0 && ticks.length > 1) {
      final filtered = <OiTick<T>>[ticks.first];
      for (var i = 1; i < ticks.length; i++) {
        if ((ticks[i].position - filtered.last.position).abs() >=
            minSpacingPx) {
          filtered.add(ticks[i]);
        }
      }
      ticks = filtered;
    }
    return ticks;
  }

  /// Returns a copy of this scale with the domain constrained to
  /// [min] and [max].
  OiChartScale<T> withDomain(T min, T max);

  /// Clamps a pixel [value] to [rangeMin]–[rangeMax] when [clamp] is true.
  @protected
  double clampPixel(double value) {
    if (!clamp) return value;
    final lo = math.min(rangeMin, rangeMax);
    final hi = math.max(rangeMin, rangeMax);
    return value.clamp(lo, hi);
  }

  /// Infers the appropriate scale type from a list of sample [values].
  ///
  /// - [DateTime] values → `OiTimeScale`
  /// - [num] values → `OiLinearScale`
  /// - [String] values → `OiCategoryScale`
  ///
  /// Returns `null` if [values] is empty or contains an unsupported type.
  static OiScaleType? inferType(List<Object> values) {
    if (values.isEmpty) return null;
    final first = values.first;
    if (first is DateTime) return OiScaleType.time;
    if (first is num) return OiScaleType.linear;
    if (first is String) return OiScaleType.category;
    return null;
  }
}
