import 'dart:convert';

import 'package:flutter/gestures.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:obers_ui/obers_ui.dart';

import '../../../helpers/paint_pixels.dart';
import 'oi_button_evidence_fixture.dart';

// Measured from the clean original implementation before extraction, with
// real blur enabled. Not generated by this test and never conditionally bypassed.
const _original =
    '365762285,3281039004,365762285,329372597,'
    '2376920909,1836882181,2376920909,2617283733,'
    '2294754309,4121143921,2294754309,1582730813,'
    '644945181,2290537807,644945181,1957526749,'
    '904799773,2372893589,904799773,434587485,'
    '4219181885,2362816933,4219181885,3310732413';

void main() {
  testWidgets('real-blur hover pixels retain original button controls', (
    tester,
  ) async {
    final previous = debugDisableShadows;
    final mouse = await tester.createGesture(kind: PointerDeviceKind.mouse);
    await mouse.addPointer(location: Offset.zero);
    final measured = <int>[];
    try {
      for (final dark in [false, true]) {
        final base = dark ? OiThemeData.dark() : OiThemeData.light();
        final theme = base.copyWith(
          effects: base.effects.copyWith(
            hover: const OiInteractiveStyle(
              backgroundOverlay: Color(0x00000000),
              halo: OiHaloStyle(
                color: Color(0xff7856a8),
                spread: 2,
                blur: 8,
                opacity: .35,
              ),
            ),
          ),
        );
        for (final size in OiButtonSize.values) {
          for (final consumer in ['normal', 'split', 'countdown', 'confirm']) {
            final button = switch (consumer) {
              'normal' => OiButton.primary(
                key: buttonEvidenceKey,
                label: 'Action Hg',
                size: size,
              ),
              'split' => OiButton.split(
                key: buttonEvidenceKey,
                label: 'Action Hg',
                size: size,
                onTap: () {},
                dropdown: const SizedBox(),
              ),
              'countdown' => OiButton.countdown(
                key: buttonEvidenceKey,
                label: 'Action Hg',
                size: size,
                onTap: () {},
                seconds: 0,
              ),
              _ => OiButton.confirm(
                key: buttonEvidenceKey,
                label: 'Action Hg',
                size: size,
                confirmLabel: 'Confirm Hg',
                onConfirm: () {},
              ),
            };
            Future<PaintPixels> capture({required bool disabled}) async {
              debugDisableShadows = disabled;
              await mouse.moveTo(Offset.zero);
              await captureButtonEvidence(tester, button, theme: theme);
              await mouse.moveTo(
                tester.getCenter(find.byKey(buttonEvidenceKey)),
              );
              await tester.pump(const Duration(milliseconds: 250));
              return captureButtonEvidence(tester, button, theme: theme);
            }

            final unblurred = await capture(disabled: true);
            final real = await capture(disabled: false);
            final changed = List.generate(real.bytes.length, (index) => index)
                .where((index) => real.bytes[index] != unblurred.bytes[index])
                .length;
            expect(changed, greaterThan(0), reason: 'Real blur must render');
            measured.add(real.fingerprint);
            debugPrint(
              jsonEncode({
                'realShadow':
                    '${dark ? 'dark' : 'light'}-${size.name}-$consumer',
                'fnv1a32': real.fingerprint,
                'unblurredVsRealChangedChannels': changed,
                'phaseMs': 250,
                'frame': [real.width, real.height],
              }),
            );
            expect(tester.takeException(), isNull);
          }
        }
      }
      expect(measured, _original.split(',').map(int.parse).toList());
    } finally {
      debugDisableShadows = previous;
      await mouse.removePointer();
      await tester.pumpWidget(const SizedBox());
    }
  });
}
